name: Import open source standard labels

on:
  push:
    branches: [ main ]

jobs:
  labels:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        node-version: '14'
    - uses: actions/labeler@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        owner-name: 'akebu6'
        repository-name: 'FYP'
        # force: true # optional to clear existing labels, default to true
